#!/usr/bin/env python3
"""
scripts/plot_difficulty_distribution.py

Simple matplotlib-only plot of the Motion Difficulty Score distribution
(for the full ~22K AMASS motions after running compute_difficulty_score.py).

This project is based on "AMP: Adversarial Motion Priors for Stylized Physics-Based Character Control" and "Perpetual Humanoid Control for Real-time Simulated Avatars". Beyond the existing projects, you introduced 64 body-shape variations and two genders, so each motion has 128 variations generated by the HUMOS model using the AMASS dataset. The repo for this project is https://github.com/hansen1416/hhi. Your ultimate goal is to build a model that converts all of non-physical motion like the AMASS dataset to physical motion.
"""

import pickle
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

def plot_difficulty_distribution():
    pkl_path = Path("data/difficulty_scores.pkl")
    if not pkl_path.exists():
        raise FileNotFoundError(f"❌ {pkl_path} not found. Run compute_difficulty_score.py first!")

    # Load the rich pickle
    with open(pkl_path, "rb") as f:
        data = pickle.load(f)

    scores_dict = data["motion_scores"]
    
    # Extract normalized scores into a simple numpy array (no pandas needed)
    norm_scores = []
    for feats in scores_dict.values():
        if "normalized_score" in feats:
            norm_scores.append(feats["normalized_score"])
    
    scores = np.array(norm_scores)
    print(f"✅ Loaded {len(scores)} motions with difficulty scores")
    print(f"   Score range (normalized): {scores.min():.4f} — {scores.max():.4f}")
    print(f"   Mean / Median: {scores.mean():.4f} / {np.median(scores):.4f}")
    print(f"   Std: {scores.std():.4f}")

    # === Plotting (pure matplotlib - no seaborn) ===
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # Left: Histogram
    axes[0].hist(scores, bins=50, density=True, color="#1f77b4", alpha=0.8, edgecolor="black")
    axes[0].axvline(scores.mean(), color="red", linestyle="--", linewidth=2, label=f"Mean = {scores.mean():.3f}")
    axes[0].axvline(np.median(scores), color="orange", linestyle="-.", linewidth=2, label=f"Median = {np.median(scores):.3f}")
    axes[0].set_title("Distribution of Normalized Motion Difficulty Scores\n(0 = easiest, 1 = hardest)", fontsize=14, pad=20)
    axes[0].set_xlabel("Normalized Difficulty Score")
    axes[0].set_ylabel("Density")
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Right: Boxplot
    axes[1].boxplot(scores, vert=True, patch_artist=True,
                    boxprops=dict(facecolor="#1f77b4", color="black"),
                    medianprops=dict(color="orange", linewidth=2))
    axes[1].set_title("Boxplot of Difficulty Scores", fontsize=14, pad=20)
    axes[1].set_ylabel("Normalized Difficulty Score")
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()

    # Save figure
    plot_dir = Path("data/plots")
    plot_dir.mkdir(parents=True, exist_ok=True)
    out_path = plot_dir / "difficulty_score_distribution.png"
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    print(f"📊 Plot saved → {out_path}")

    # Optional: also save as PDF for papers
    plt.savefig(plot_dir / "difficulty_score_distribution.pdf", dpi=300, bbox_inches="tight")
    plt.show()


if __name__ == "__main__":
    plot_difficulty_distribution()